### ISSUE TITLE
littleEndian support needed.

### ISSUE THREAD

**Issue by louderspace** [joeltg/fp16#1]
I'm testing on a mac and reading data back from the GPU.  These routines don't work without the littleEndian parameter passed as true.

Basically, every call to setUint16 and getUint16 on the DataView needs the littleEndian parameter.  To support that, setFloat16 and getFloat16 need a littleEndian option as well.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getUint16#littleendian

**Comment by joeltg** [comment]
Makes sense, I just published v0.3.0 with support for this. I pretty sure I'm testing it right but if you could confirm that it works for you I'd appreciate it.

**Comment by louderspace** [comment]
Wonderful!  I've tested the change and can now validate my float16's written and read back from WebGPU textures.  Thank you :)
